Repository jenkinsci/windows-slave-installer-module, pull requests merged in 2020-06, with the labels that each got.

#48 [JEP-15] - Add Jenkins sponsorship metadata to the repository
  .github/FUNDING.yml
Labels: chore

#46 Spotbugs suppression spelling fix
  src/main/java/org/jenkinsci/modules/windows_slave_installer/SlaveExeUpdater.java
Labels: chore

#42 Update Windows Service Wrapper from 2.3.0 to 2.9.0
  pom.xml
Labels: dependencies

#43 [JENKINS-60005, JENKINS-61862] - Update for Windows Service Wrapper 2.8.0
  pom.xml
  src/main/java/org/jenkinsci/modules/windows_slave_installer/WindowsSlaveInstaller.java
  src/main/resources/org/jenkinsci/modules/windows_slave_installer/jenkins-slave.exe.config
  src/test/java/org/jenkinsci/modules/windows_slave_installer/WindowsSlaveInstallerTest.java
Labels: enhancement, removed

#50 Update to Plugin POM 4.x
  pom.xml
Labels: chore

#51 Add Visual Studio Code files to .gitignore
  .gitignore
Labels: chore

#52 Update documentation and messages to reflect the Windows support policy
  README.md
  src/main/resources/org/jenkinsci/modules/windows_slave_installer/Messages.properties
Labels: documentation
